In [4]:
import numpy as np

In [5]:
np.array(3)#标量
np.array([1,2,3]) #向量
np.array([1,2,3],[4,5,6]) #矩阵

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
np.random.rand() #0-1之间采样的随机数（均匀分布上采样）
np.random.randn()  #在标准正态分布上采样的随机数
np.random.randint(1,10) #左闭右开，1-10之间的整数采样
np.random.uniform(1.0,2.0) #左闭右开，均匀分布采样
'''
import random
#不要用，可以认为设计缺陷
random.randint(1,3) #左闭右闭，
'''

'\nimport random\n#不要用，可以认为设计缺陷\nrandom.randint(1,3) #左闭右闭，\n'

In [6]:
np.random.randn(3,2) #二维张量
# np.random.randint(1,10,size=(3,2,5))

array([[ 0.07700099, -0.38565499],
       [-0.49917204, -0.77324069],
       [ 0.45333208, -2.55660186]])

In [ ]:
l=list(range(10))
np.array(l)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#0矩阵,默认浮点型
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 全是1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#上三角
np.triu(np.random.randn(4,4))
# 下三角
np.tril(np.random.randn(4,4))

array([[-0.56928626, -1.66298083, -2.18696712,  1.01117826],
       [ 0.        , -0.15909814,  0.28843106, -1.39474535],
       [ 0.        ,  0.        ,  1.15518607, -0.14197931],
       [ 0.        ,  0.        ,  0.        ,  0.28095451]])

In [ ]:
t6=np.array([np.random.randn() for i in range(10)])
print(t6)
t7=np.round(t6,4)# 取小数，给定参数位数
print(t7)

[-1.78100737 -1.10932733 -1.10349808  0.60276189 -1.94685204 -1.14790332
 -0.77478698 -1.80159371 -0.8459449   1.94591689]
[-1.781  -1.1093 -1.1035  0.6028 -1.9469 -1.1479 -0.7748 -1.8016 -0.8459
  1.9459]


In [ ]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a=np.random.randn(5,6)
b=np.zeros_like(a) #创建一个形状和a相同的
b,b.shape

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 (5, 6))

### 在指定间隔里线性间隔

In [ ]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# 排序
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])