In [2]:
import numpy as np

a=np.random.randn(3,4,5)
print(a)

[[[ 1.46449119  2.53930164 -0.02503208  0.28483563 -1.5831194 ]
  [ 0.08286872  2.29066852  0.03180682 -1.61671536  2.16250192]
  [ 2.01112233  0.63233851  1.15970583 -1.01043761 -0.01921521]
  [ 0.02039354  1.97083004  0.37112022 -0.09950814 -0.57678585]]

 [[-0.75831745  0.22612331  0.75215347 -0.53053409  0.97325564]
  [-0.10883157  1.28683887 -0.81199999  1.70118502 -1.18438109]
  [ 0.80928256 -1.08217737  0.55284987  0.34173785  1.17040335]
  [ 0.14515062  0.2837415   0.21616993  1.01674018  0.04422346]]

 [[ 1.37903192  0.66231779  0.33725828 -0.29156273  0.15055091]
  [-0.33319544 -0.58704367 -0.550337   -0.59191555  0.37491564]
  [ 0.39614887 -0.69810287  1.94576832  0.67067076 -0.16989424]
  [ 0.37600792  0.54616704  0.02289344 -0.15435359  1.08903711]]]


In [3]:
a.shape
a.dtype #float64
a.ndim # 维度
a.size

60

In [8]:
# 修改类型
a.astype(dtype=np.float16)



array([[[ 1.465  ,  2.54   , -0.02504,  0.285  , -1.583  ],
        [ 0.0829 ,  2.291  ,  0.0318 , -1.617  ,  2.162  ],
        [ 2.012  ,  0.6323 ,  1.16   , -1.011  , -0.01921],
        [ 0.0204 ,  1.971  ,  0.371  , -0.0995 , -0.5767 ]],

       [[-0.7583 ,  0.2261 ,  0.752  , -0.531  ,  0.973  ],
        [-0.1088 ,  1.287  , -0.812  ,  1.701  , -1.185  ],
        [ 0.809  , -1.082  ,  0.5527 ,  0.3418 ,  1.17   ],
        [ 0.1451 ,  0.2837 ,  0.2162 ,  1.017  ,  0.04422]],

       [[ 1.379  ,  0.662  ,  0.3372 , -0.2915 ,  0.1505 ],
        [-0.3333 , -0.587  , -0.5503 , -0.592  ,  0.375  ],
        [ 0.3962 , -0.698  ,  1.945  ,  0.671  , -0.1699 ],
        [ 0.376  ,  0.5464 ,  0.02289, -0.1543 ,  1.089  ]]],
      dtype=float16)