In [1]:
import numpy as np


In [3]:
a=np.random.randn(3,4)
print(a)

[[ 0.43409943 -0.78065792 -0.76493203 -0.07343471]
 [-1.48198789  0.1711085   0.40260683  2.05116822]
 [-0.64809775 -0.75953842  1.61612163 -2.20930184]]


In [4]:
a[:,:2]

array([[ 0.43409943, -0.78065792],
       [-1.48198789,  0.1711085 ],
       [-0.64809775, -0.75953842]])