In [2]:
import numpy as np

In [3]:
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)
print(a)
print(b)
# 第一种连接,形状要一样,维度增加
np.stack([a,b])
np.stack((a,b),axis=1)
# np.stack((a,b,b),axis=2) #可以并好几个


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [4]:
# 第二种连接
a=np.arange(12).reshape(3,4)
b=np.arange(12,24).reshape(3,4)
print(a)
print(b)

np.concatenate((a,b),axis=0)
np.concatenate((a,b),axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])