In [1]:
import numpy as np


In [2]:
t1=np.arange(12)
print(t1)
t1.shape # 查看形状
t1.reshape((3,4))


[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
t2=np.arange(24).reshape(2,3,4)# 参数分别是块数、行数、列数，数字的个数代表维度
t2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
t2.flatten() #将数组按行展开成一维

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
t2+2 #数组加法，给所有元素都加2


array([[[ 2,  3,  4,  5],
        [ 6,  7,  8,  9],
        [10, 11, 12, 13]],

       [[14, 15, 16, 17],
        [18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [16]:
t2/2


array([[[ 0. ,  0.5,  1. ,  1.5],
        [ 2. ,  2.5,  3. ,  3.5],
        [ 4. ,  4.5,  5. ,  5.5]],

       [[ 6. ,  6.5,  7. ,  7.5],
        [ 8. ,  8.5,  9. ,  9.5],
        [10. , 10.5, 11. , 11.5]]])

In [9]:
np.random.rand(2,3,4)
np.random.uniform(2,5,size=(3,4,5))

array([[[2.43735165, 2.34057994, 2.59188885, 4.22951612, 2.94322754],
        [2.18807742, 4.37240376, 2.98524275, 4.85056002, 3.07564774],
        [3.30591447, 4.34333776, 2.56021101, 3.02466362, 4.84595139],
        [4.98686655, 3.74539075, 4.68878161, 4.98271936, 2.32433017]],

       [[4.59779135, 2.91755554, 4.29120243, 3.61283433, 2.63181439],
        [3.34010803, 3.26713945, 2.72294526, 2.86145666, 2.68655171],
        [3.64186548, 4.71863111, 2.9555938 , 2.02111688, 3.11073563],
        [2.48897821, 3.46599664, 4.71127027, 3.14993705, 2.36408254]],

       [[4.01479057, 2.84355921, 3.16238744, 4.13998438, 4.68295328],
        [4.2923563 , 4.08924954, 4.90545065, 3.65465953, 3.02513979],
        [4.15466274, 3.12747934, 2.31584553, 3.1393399 , 2.65572221],
        [3.65584993, 4.92808034, 4.06271286, 3.29076061, 4.78619036]]])

In [11]:
np.zeros((2,3,4))
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [17]:
np.empty(2)

array([1.5e-323, 2.0e-323])

In [9]:
np.random.randint(1,3,size=(3,2,4)).swapaxes(1,2)

array([[[2, 1],
        [1, 2],
        [1, 1],
        [1, 1]],

       [[2, 1],
        [2, 1],
        [2, 2],
        [2, 2]],

       [[1, 2],
        [1, 1],
        [1, 1],
        [2, 2]]])

##### np.loadtxt(frame,dtype=np.float,delimiter=None,skipprows=0,usecols=None,unpack=False)
skiprows 跳过开头x行，一般跳过开头第一行
usecols读取指定数列，索引，元组类型
